Repository asyncapi/server-api, pull requests merged in 2022-03, with the labels that each got.

#74 docs: updated readme banner
  .github/assets/banner.png
  README.md
Labels: ready-to-merge

#73 feat: serve openapi.yaml file as documentation page
  .eslintignore
  package-lock.json
  package.json
  src/app.ts
  src/constants.ts
  src/controllers/docs.controller.ts
  src/server.ts
Labels: ready-to-merge

#75 chore: add all-contributors section
  .all-contributorsrc
  README.md
Labels: ready-to-merge, 📑 docs

#76 docs: add docker section in the Readme
  Dockerfile
  README.md
  package.json
Labels: ready-to-merge, 📑 docs

#71 chore: added Liveliness and Readiness Probes to K8S deployment
  deployments/k8s/templates/deployment.yaml
  deployments/k8s/values.yaml
Labels: ready-to-merge

#26 feat: add /convert path
  .eslintignore
  openapi.yaml
  package-lock.json
  package.json
  src/controllers/convert.controller.ts
  src/controllers/tests/convert.controller.test.ts
  src/controllers/tests/validate.controller.test.ts
  src/interfaces.ts
  src/middlewares/document-validation.middleware.ts
  src/server.ts
  src/services/convert.service.ts
  src/services/tests/convert.service.test.ts
Labels: ready-to-merge

#78 refactor: combine asyncapi validation with request body
  openapi.yaml
  package-lock.json
  package.json
  src/app.ts
  src/controllers/convert.controller.ts
  src/controllers/generate.controller.ts
  src/controllers/tests/convert.controller.test.ts
  src/controllers/tests/generate.controller.test.ts
  src/controllers/tests/validate.controller.test.ts
  src/controllers/validate.controller.ts
  src/interfaces.ts
  src/middlewares/document-validation.middleware.ts
  src/middlewares/request-body-validation.middleware.ts
  src/middlewares/tests/document-validation.middleware.test.ts
  src/middlewares/tests/problem.middleware.test.ts
  src/middlewares/tests/request-body-validation.middleware.test.ts
  src/middlewares/tests/validation.middleware.test.ts
  src/middlewares/validation.middleware.ts
  src/server.ts
  src/utils/ajv.ts
Labels: enhancement, ready-to-merge

#70 feat: add /bundle endpoint
  openapi.yaml
  package-lock.json
  package.json
  src/controllers/bundle.controller.ts
  src/controllers/tests/bundle.controller.test.ts
  src/server.ts
Labels: ready-to-merge
