Repository asyncapi/server-api, pull requests merged in 2022-01, with the labels that each got.

#24 feat: add Dockerfile
  .dockerignore
  .gitignore
  Dockerfile
  jest.config.js
  package-lock.json
  package.json
  src/app.ts
  src/server.ts
  tsconfig.json
  tsconfig.test.json
Labels: enhancement

#22 feat: add /validate path
  openapi.yaml
  src/controllers/generate.controller.ts
  src/controllers/tests/generator.controller.test.ts
  src/controllers/tests/validate.controller.test.ts
  src/controllers/validate.controller.ts
  src/middlewares/document-validation.middleware.ts
  src/middlewares/request-body-validation.middleware.ts
  src/server.ts
  src/services/tests/generator.service.test.ts
  src/utils/parser.ts
  tests/test.controller.ts
Labels: enhancement, ready-to-merge

#37 fix: force 2 version of packageLock in the package-lock.json
  Dockerfile
Labels: bug

#25 ci: add K8S deployment
  deployments/k8s/.helmignore
  deployments/k8s/Chart.yaml
  deployments/k8s/README.md
  deployments/k8s/templates/NOTES.txt
  deployments/k8s/templates/_helpers.tpl
  deployments/k8s/templates/deployment.yaml
  deployments/k8s/templates/hpa.yaml
  deployments/k8s/templates/ingress.yaml
  deployments/k8s/templates/service.yaml
  deployments/k8s/values.yaml
Labels: enhancement
